### PR TITLE
Update deployment-script-files-solution-deployment-config-settings.md

### PR DESCRIPTION
**Pull request by greijer**
The .configsettings is not generated when building the project. It has to be manually created using the deployment wizard in answer mode. I have updated the document to reflect this

### CODE REVIEW

**Comment by PRMerger6** [comment]
@greijer : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by Minewiskan** [comment]
#in-progress
Tech review

**Comment by Minewiskan** [comment]
@greijer - Are you deploying in multidimensional or tabular mode?

**Comment by greijer** [comment]
@Minewiskan I'm building the multi dimensional project using visual studio 2019, and the stated artifact is not produced (.configsettings)

**Comment by greijer** [comment]
Sorry..mistakenly wrote "multi dimensional" at first comment :-) it should be " tabular"

**Review by Minewiskan — COMMENTED** [review]
@greijer - Apparently the configsettings file is created with build for multidimensional projects but not for tabular. I can approve and merge your changes, then go in after and make additional changes to reflect the difference or we can cancel your PR and I can make all the changes. Let me know which you prefer. Thank you.

**Comment by greijer** [comment]
Hi
It seem cleaner to cancel mine and you make the correct changes.
If this is ok with you
Man thanks
Joel

**Comment by Minewiskan** [comment]
Resolved in https://github.com/MicrosoftDocs/bi-shared-docs-pr/pull/536. Closing this PR. More work will have to be done in other files as part of another separate PR in private repo.

**Pull request closed without merging**
