### PR TITLE
Update configure-service-accounts for SSAS

### PR DESCRIPTION
**Pull request by arcus4**
Instead of using the built-in account, we would like to run SSAS services with a MSA as in other installations (SQL, PBIRS). https://learn.microsoft.com/en-us/analysis-services/instances/spn-registration-for-an-analysis-services-instance?view=asallproducts-allversions#bkmk_SPNSyntax lists all possible SSAS Service Accounts and this information could be helpful here as well.

### CODE REVIEW

**Comment by Court72** [comment]
@kfollis

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Review by jonburchel — APPROVED** [review]

**Comment by kfollis** [comment]
[heart]         Kate Follis reacted to your message:
________________________________

**Comment by jonburchel** [comment]
#assign jonburchel

**Comment by jonburchel** [comment]
#add-assignee jonburchel

**Comment by kfollis** [comment]
@arcus4 - thank you for the contribution! These changes are being published from our internal branch, so closing this PR.
#please-close

**Pull request closed without merging**
