### PR TITLE
LinkFix: bi-shared-docs (2021-11)

### PR DESCRIPTION
**Pull request by cmcclister**
This PR is the result of running a Link Repair script on the included content. This script is primarily being run to clean up links to function correctly in Air Gapped Clouds (AGC). Here's a breakdown of what the script that generated the changes in this PR fixes: 

 

- docs.microsoft.com Fully Qualified Domain Name (FQDN) Links to either Relative (if in same Repo/DocSet/ContentSet) and Site Relative if not 

- azure.microsoft.com/documentation/articles that reflect to Docs to either Relative (if in same Repo/DocSet/ContentSet) and Site Relative if not 

- All known flavors of MSDN/TechNet domains (we know of 8 or 9 now) that reflect to Docs to either Relative (if in same Repo/DocSet/ContentSet) and Site Relative if not 

  - This also includes cleanup of the appended query string for MSDN (redirectedfrom=MSDN). 

- Fixes articles that are redirected in `.openpublishing.redirection.json` and updates the link to the current final location (this has a lot of customer usability fixes). 

 

Please note the [Contributor Guide: Links](https://review.docs.microsoft.com/en-us/help/contribute/links-how-to?branch=master) has been updated with the following link-type preference order: 

 

``` 

By order of preference, links hosted on Docs should be Relative if they are in the same repository and docset. If they are in a different docset, even if in the same repository, they should be Site Relative. Links to content hosted on Docs shouldn't use a complete URL, otherwise known as Fully Qualified Domain Names (FQDN). Using a complete URL from Docs to other content on Docs will cause that link to be non-functional in air-gap environments. 

```

### CODE REVIEW

**Comment by PRMerger17** [comment]
@v-chmccl : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Minewiskan** [comment]
@v-chmccl - Is there a reason why you did this in the public repo? We're having some problems with synchronization from public to private, so it's probably best this fix is made in the private repo. However, for some reason, I couldn't get this particular to work as a relative link (https://github.com/MicrosoftDocs/bi-shared-docs-pr/pull/508). Urgency to get this published forced me to use a regular link.

**Comment by cmcclister** [comment]
Hi @Minewiskan, per [this document](https://microsoft.sharepoint.com/:x:/r/teams/globalproduction/_layouts/15/Doc.aspx?sourcedoc=%7bcb31bfb3-b75e-4ad3-b9d9-15918c97340d%7d&action=default&uid=%7bCB31BFB3-B75E-4AD3-B9D9-15918C97340D%7d&ListItemId=1979&ListId=%7b9FD94A20-2488-4F0D-9698-A7E6D9FD5F42%7d&odsp=1&env=prodbubble&cid=a221656b-a0ee-438c-a49f-6dfacc6d2f1c), if you see row 72, the public repo is specified. If this is incorrect, please coordinate with @georgewallace or @snoviking and we can update the information in the tracking spreadsheet. Thanks! cc @kfollis

**Comment by Minewiskan** [comment]
@v-chmccl - I was able to fix the link in the private repo and merge though to live. https://github.com/MicrosoftDocs/bi-shared-docs-pr/pull/511. Not sure why it validated this time but not in the initial PR. I did the exact same thing. Go figure. You can close out this PR since it has now synced with the public repo.

**Pull request closed without merging**
